





:class:`LSDYNATerminationError`
===============================

.. py:exception:: ansys.heart.core.exceptions.LSDYNATerminationError

   Bases: :py:obj:`BaseException`


   
   Exception raised when `Normal Termination` is not found in the LS-DYNA logs.
















   ..
       !! processed by numpydoc !!



Import detail
-------------

.. code-block:: python

    from ansys.heart.core.exceptions import LSDYNATerminationError





